Q1. Understanding Feature Distributions (Iris Dataset)

Context: Before training any ML model, we analyze feature distributions.

Dataset: Load Iris dataset from sklearn

Tasks:

1. Extract feature matrix as NumPy array
2. Compute:
Mean
Median
Standard deviation
Variance (for each feature)
3. Identify:
Which feature has highest variability and why it matters in ML
4. Convert any one feature into shape (n,1) and explain why ML models expect this format

In [3]:
import numpy as np
from sklearn.datasets import load_iris

# Load dataset
iris = load_iris()
X = iris.data   # Feature matrix (NumPy array)
feature_names = iris.feature_names

# 1. Check shape of feature matrix
print("Feature Matrix Shape:", X.shape)  # (150, 4)

# 2. Compute statistics for each feature
mean = np.mean(X, axis=0)
median = np.median(X, axis=0)
std_dev = np.std(X, axis=0)
variance = np.var(X, axis=0)

# Print results
print("\nFeature Statistics:\n")
for i, feature in enumerate(feature_names):
    print(f"{feature}:")
    print(f"  Mean      = {mean[i]:.3f}")
    print(f"  Median    = {median[i]:.3f}")
    print(f"  Std Dev   = {std_dev[i]:.3f}")
    print(f"  Variance  = {variance[i]:.3f}\n")

# 3. Identify feature with highest variability
max_var_index = np.argmax(variance)
print("Feature with highest variability:", feature_names[max_var_index])
print("Variance:", variance[max_var_index])

# 4. Convert one feature into shape (n,1)
sepal_length = X[:, 0]              # shape (150,)
sepal_length_reshaped = sepal_length.reshape(-1, 1)

print("\nOriginal shape:", sepal_length.shape)
print("Reshaped to (n,1):", sepal_length_reshaped.shape)

Feature Matrix Shape: (150, 4)

Feature Statistics:

sepal length (cm):
  Mean      = 5.843
  Median    = 5.800
  Std Dev   = 0.825
  Variance  = 0.681

sepal width (cm):
  Mean      = 3.057
  Median    = 3.000
  Std Dev   = 0.434
  Variance  = 0.189

petal length (cm):
  Mean      = 3.758
  Median    = 4.350
  Std Dev   = 1.759
  Variance  = 3.096

petal width (cm):
  Mean      = 1.199
  Median    = 1.300
  Std Dev   = 0.760
  Variance  = 0.577

Feature with highest variability: petal length (cm)
Variance: 3.0955026666666674

Original shape: (150,)
Reshaped to (n,1): (150, 1)


Q2. Data Selection for Model Input

Context: Models are trained on selective features, not full raw data.

Dataset: Iris

Tasks:

1. Extract:
First 100 samples
Only last 2 features
2. Use boolean masking:
Select samples where petal length is greater than dataset mean
3. Count selected samples
4. Explain how this relates to feature-based filtering in ML

In [2]:
import numpy as np
from sklearn.datasets import load_iris

iris = load_iris()
X = iris.data
feature_names = iris.feature_names

# 1. Extract first 100 samples and last 2 features
subset = X[:100, -2:]   # rows 0-99, last 2 columns

print("Subset Shape (first 100 samples, last 2 features):", subset.shape)

# 2. Boolean masking: petal length > mean
petal_length = X[:, 2]  # petal length column

mean_petal_length = np.mean(petal_length)
mask = petal_length > mean_petal_length

selected_samples = X[mask]

# 3. Count selected samples
count = np.sum(mask)

print("\nMean Petal Length:", round(mean_petal_length, 3))
print("Number of selected samples:", count)
print("Selected Samples Shape:", selected_samples.shape)

Subset Shape (first 100 samples, last 2 features): (100, 2)

Mean Petal Length: 3.758
Number of selected samples: 93
Selected Samples Shape: (93, 4)


Q3. Feature Scaling using NumPy (Very Important)

Context: Most ML models require normalized data.

Dataset: Iris (NumPy array)

Tasks:

1. Apply standardization:

$$
X' = \frac{X - \mu}{\sigma}
$$
	​2. 

Verify:
Mean ≈ 0
Std ≈
on

In [11]:
import numpy as np
from sklearn.datasets import load_iris

# Load dataset
iris = load_iris()
X = iris.data   # shape (150, 4)

# 1. Compute mean and standard deviation (column-wise)
mean = np.mean(X, axis=0)
std = np.std(X, axis=0)

# 2. Apply standardization
X_scaled = (X - mean) / std

# 3. Verify results
scaled_mean = np.mean(X_scaled, axis=0)
scaled_std = np.std(X_scaled, axis=0)

print("Mean after scaling:", scaled_mean)
print("Std after scaling:", scaled_std)

Mean after scaling: [-1.69031455e-15 -1.84297022e-15 -1.69864123e-15 -1.40924309e-15]
Std after scaling: [1. 1. 1. 1.]


Q4. Dataset Understanding (Titanic Dataset)

Context: First step in ML pipeline is dataset inspection.

Dataset: Titanic (Seaborn)

Tasks:

1. Display:
head(), tail()
info(), describe()
2. Identify:
Missing values per column
Numerical vs categorical features
3. Explain:
Why identifying feature types is important before modeling

In [12]:
import pandas as pd
import seaborn as sns

# Load Titanic dataset
df = sns.load_dataset('titanic')

# 1. Display basic data
print("HEAD:\n", df.head())
print("\nTAIL:\n", df.tail())

print("\nINFO:\n")
print(df.info())

print("\nDESCRIBE (Numerical):\n", df.describe())

print("\nDESCRIBE (Including Categorical):\n", df.describe(include='all'))

# 2. Missing values per column
missing_values = df.isnull().sum()
print("\nMissing Values per Column:\n", missing_values)

# Identify numerical vs categorical features
numerical_features = df.select_dtypes(include=['int64', 'float64']).columns
categorical_features = df.select_dtypes(include=['object', 'category', 'bool']).columns

print("\nNumerical Features:\n", list(numerical_features))
print("\nCategorical Features:\n", list(categorical_features))

Matplotlib is building the font cache; this may take a moment.


HEAD:
    survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True  

TAIL:
      survived  pclass     sex   age  sibsp  parch   fare embarked   class  \
886         0       2    male  27.0      0      0  13.00        S  Second   
887         1       1  female  19.0      0      0 

Q5. Filtering Data for Business Logic

Context: Real ML problems require filtering relevant populations.

Dataset: Titanic

Tasks:

1. Filter:
Female passengers in 1st class
2. Compute:
Survival rate for this group
3. Compare with overall survival rate
4. Interpret:
What insight can be used in ML feature engineering

In [13]:
import pandas as pd
import seaborn as sns

# Load dataset
df = sns.load_dataset('titanic')

# 1. Filter: Female passengers in 1st class
female_first_class = df[(df['sex'] == 'female') & (df['class'] == 'First')]

# 2. Survival rate for this group
group_survival_rate = female_first_class['survived'].mean()

# 3. Overall survival rate
overall_survival_rate = df['survived'].mean()

print("Female 1st Class Survival Rate:", round(group_survival_rate, 3))
print("Overall Survival Rate:", round(overall_survival_rate, 3))

# Optional: count of passengers in filtered group
print("Number of Female 1st Class passengers:", len(female_first_class))

Female 1st Class Survival Rate: 0.968
Overall Survival Rate: 0.384
Number of Female 1st Class passengers: 94


Q6. Handling Missing Data (Critical ML Step)

Context: Models cannot handle null values.

Dataset: Titanic

Tasks:

1. Fill missing age using median
2. Fill missing embarked using mode
3. Drop deck column
4. Explain:
Why different strategies are used for different columns

In [14]:
import pandas as pd
import seaborn as sns

# Load dataset
df = sns.load_dataset('titanic')

# 1. Fill missing 'age' with median
df['age'] = df['age'].fillna(df['age'].median())

# 2. Fill missing 'embarked' with mode
df['embarked'] = df['embarked'].fillna(df['embarked'].mode()[0])

# 3. Drop 'deck' column
df = df.drop(columns=['deck'])

# Verify missing values are handled
print(df.isnull().sum())

survived       0
pclass         0
sex            0
age            0
sibsp          0
parch          0
fare           0
embarked       0
class          0
who            0
adult_male     0
embark_town    2
alive          0
alone          0
dtype: int64


Q7. Feature Engineering for Model Improvement

Context: Raw data is rarely useful—features must be created.

Dataset: Titanic

Tasks:

1. Create:
family_size = sibsp + parch + 1
2. Create:
is_alone (binary feature)
3. Compute survival rate by is_alone
4. Explain:
Why engineered features improve ML models

In [15]:
import pandas as pd
import seaborn as sns

# Load dataset
df = sns.load_dataset('titanic')

# 1. Create family_size
df['family_size'] = df['sibsp'] + df['parch'] + 1

# 2. Create is_alone (binary feature)
df['is_alone'] = (df['family_size'] == 1).astype(int)

# 3. Compute survival rate by is_alone
survival_by_alone = df.groupby('is_alone')['survived'].mean()

print("Survival Rate by is_alone:\n")
print(survival_by_alone)

Survival Rate by is_alone:

is_alone
0    0.505650
1    0.303538
Name: survived, dtype: float64


Q8. Group-Based Insights (Customer Segmentation Logic)

Context: ML models often depend on aggregated patterns.

Dataset: Tips

Tasks:

1. Compute:
Average tip by day
Total bill by gender
2. Create new feature:
tip_percentage
3. Identify:
Which day has highest tipping behavior
4. Explain:
How this helps in segmentation models

In [16]:
import pandas as pd
import seaborn as sns

# Load dataset
df = sns.load_dataset('tips')

# 1. Compute aggregations

# Average tip by day
avg_tip_by_day = df.groupby('day')['tip'].mean()

# Total bill by gender
total_bill_by_gender = df.groupby('sex')['total_bill'].sum()

print("Average Tip by Day:\n", avg_tip_by_day)
print("\nTotal Bill by Gender:\n", total_bill_by_gender)

# 2. Create new feature: tip_percentage
df['tip_percentage'] = (df['tip'] / df['total_bill']) * 100

# 3. Identify day with highest tipping behavior
tip_pct_by_day = df.groupby('day')['tip_percentage'].mean()
best_day = tip_pct_by_day.idxmax()

print("\nAverage Tip % by Day:\n", tip_pct_by_day)
print("\nDay with Highest Tipping Behavior:", best_day)

Average Tip by Day:
 day
Thur    2.771452
Fri     2.734737
Sat     2.993103
Sun     3.255132
Name: tip, dtype: float64

Total Bill by Gender:
 sex
Male      3256.82
Female    1570.95
Name: total_bill, dtype: float64

Average Tip % by Day:
 day
Thur    16.127563
Fri     16.991303
Sat     15.315172
Sun     16.689729
Name: tip_percentage, dtype: float64

Day with Highest Tipping Behavior: Fri


/var/folders/f2/j3l_llfs2fqgphpwqhb93j7w0000gn/T/ipykernel_36594/4042988463.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  avg_tip_by_day = df.groupby('day')['tip'].mean()
/var/folders/f2/j3l_llfs2fqgphpwqhb93j7w0000gn/T/ipykernel_36594/4042988463.py:13: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  total_bill_by_gender = df.groupby('sex')['total_bill'].sum()
/var/folders/f2/j3l_llfs2fqgphpwqhb93j7w0000gn/T/ipykernel_36594/4042988463.py:22: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior 

Q9. Advanced Filtering + Subsetting

Context: Training data is often filtered based on business rules.

Dataset: Tips

Tasks:

1. Filter:
total_bill > 20 AND tip < 3
2. Select only relevant columns
3. Analyze:
Is this segment under-tipping?
4. Explain:
How such filtering helps anomaly detection

In [17]:
import pandas as pd
import seaborn as sns

# Load dataset
df = sns.load_dataset('tips')

# 1. Filter: total_bill > 20 AND tip < 3
filtered_df = df[(df['total_bill'] > 20) & (df['tip'] < 3)]

# 2. Select only relevant columns
subset = filtered_df[['total_bill', 'tip', 'tip_percentage']] if 'tip_percentage' in df.columns else filtered_df[['total_bill', 'tip']]

# (Optional) create tip_percentage if not already created
subset['tip_percentage'] = (subset['tip'] / subset['total_bill']) * 100

# 3. Analyze
avg_tip_pct = subset['tip_percentage'].mean()
overall_tip_pct = (df['tip'] / df['total_bill'] * 100).mean()

print("Filtered Segment Size:", len(subset))
print("Avg Tip % (Filtered):", round(avg_tip_pct, 2))
print("Avg Tip % (Overall):", round(overall_tip_pct, 2))

Filtered Segment Size: 21
Avg Tip % (Filtered): 9.08
Avg Tip % (Overall): 16.08


/var/folders/f2/j3l_llfs2fqgphpwqhb93j7w0000gn/T/ipykernel_36594/1652970714.py:14: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  subset['tip_percentage'] = (subset['tip'] / subset['total_bill']) * 100


Q10. Data Transformation for Model Input (NumPy)

Context: ML models require structured numeric arrays.

Tasks:

1. Create two arrays of shape (3,2)
2. Perform:
Vertical stacking
Horizontal stacking
3. Reshape into (2,6)
4. Explain:
Why reshaping is required in ML pipelines

In [18]:
import numpy as np

# 1. Create two arrays of shape (3,2)
A = np.array([[1, 2],
              [3, 4],
              [5, 6]])

B = np.array([[7, 8],
              [9, 10],
              [11, 12]])

print("Array A:\n", A)
print("\nArray B:\n", B)

# 2. Vertical stacking (row-wise)
v_stack = np.vstack((A, B))
print("\nVertical Stack Shape:", v_stack.shape)
print(v_stack)

# 3. Horizontal stacking (column-wise)
h_stack = np.hstack((A, B))
print("\nHorizontal Stack Shape:", h_stack.shape)
print(h_stack)

# 4. Reshape into (2,6)
reshaped = h_stack.reshape(2, 6)
print("\nReshaped to (2,6):")
print(reshaped)
print("New Shape:", reshaped.shape)

Array A:
 [[1 2]
 [3 4]
 [5 6]]

Array B:
 [[ 7  8]
 [ 9 10]
 [11 12]]

Vertical Stack Shape: (6, 2)
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]

Horizontal Stack Shape: (3, 4)
[[ 1  2  7  8]
 [ 3  4  9 10]
 [ 5  6 11 12]]

Reshaped to (2,6):
[[ 1  2  7  8  3  4]
 [ 9 10  5  6 11 12]]
New Shape: (2, 6)


Q11. End-to-End ML Preprocessing Pipeline (Titanic)

Context: Prepare dataset for ML model training

Tasks:

1. Load dataset
2. Handle missing values
3. Encode categorical variables (sex, embarked)
4. Normalize numerical features
5. Convert to NumPy array

Output:

Final feature matrix ready for model training

In [19]:
import pandas as pd
import numpy as np
import seaborn as sns
from sklearn.preprocessing import StandardScaler

# 1. Load dataset
df = sns.load_dataset('titanic')

# Fill numerical
df['age'] = df['age'].fillna(df['age'].median())

# Fill categorical
df['embarked'] = df['embarked'].fillna(df['embarked'].mode()[0])

# Drop high-missing / irrelevant columns
df = df.drop(columns=['deck'])

# One-hot encoding
df_encoded = pd.get_dummies(df, columns=['sex', 'embarked'], drop_first=True)

numerical_cols = ['age', 'fare', 'sibsp', 'parch']

scaler = StandardScaler()
df_encoded[numerical_cols] = scaler.fit_transform(df_encoded[numerical_cols])

# Drop target variable if training separately
X = df_encoded.drop(columns=['survived']).values
y = df_encoded['survived'].values

print("Final Feature Matrix Shape:", X.shape)
print("Target Shape:", y.shape)

Final Feature Matrix Shape: (891, 14)
Target Shape: (891,)


Q12. Feature Selection using Statistical Understanding

Context: Not all features improve model performance.

Dataset: Iris

Tasks:

1. Compute correlation matrix
2. Identify highly correlated features
3. Drop redundant features
4. Explain:
Impact on overfitting and model performance

In [20]:
import pandas as pd
import numpy as np
from sklearn.datasets import load_iris

# Load dataset
iris = load_iris()
X = iris.data
feature_names = iris.feature_names

# Convert to DataFrame
df = pd.DataFrame(X, columns=feature_names)

# 1. Compute correlation matrix
corr_matrix = df.corr()
print("Correlation Matrix:\n", corr_matrix)

# 2. Identify highly correlated features (threshold = 0.9)
threshold = 0.9
high_corr_pairs = []

for i in range(len(corr_matrix.columns)):
    for j in range(i):
        if abs(corr_matrix.iloc[i, j]) > threshold:
            col1 = corr_matrix.columns[i]
            col2 = corr_matrix.columns[j]
            high_corr_pairs.append((col1, col2))

print("\nHighly Correlated Feature Pairs:\n", high_corr_pairs)

# 3. Drop redundant features (example: drop second feature in each pair)
to_drop = [pair[0] for pair in high_corr_pairs]
df_reduced = df.drop(columns=to_drop)

print("\nRemaining Features After Dropping:\n", df_reduced.columns.tolist())

Correlation Matrix:
                    sepal length (cm)  sepal width (cm)  petal length (cm)  \
sepal length (cm)           1.000000         -0.117570           0.871754   
sepal width (cm)           -0.117570          1.000000          -0.428440   
petal length (cm)           0.871754         -0.428440           1.000000   
petal width (cm)            0.817941         -0.366126           0.962865   

                   petal width (cm)  
sepal length (cm)          0.817941  
sepal width (cm)          -0.366126  
petal length (cm)          0.962865  
petal width (cm)           1.000000  

Highly Correlated Feature Pairs:
 [('petal width (cm)', 'petal length (cm)')]

Remaining Features After Dropping:
 ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)']


Q13. Custom Feature Transformation using apply()

Context: Real ML requires custom logic transformation.

Dataset: Titanic

Tasks:

1. Create age_group:
Child / Adult / Senior
2. Use .apply()
3. Compute survival rate per group
4. Interpret:
Which segment has highest survival likelihood

In [21]:
import pandas as pd
import seaborn as sns

# Load dataset
df = sns.load_dataset('titanic')

# Fill missing age (needed before transformation)
df['age'] = df['age'].fillna(df['age'].median())

# 1 & 2. Create age_group using .apply()
def categorize_age(age):
    if age < 18:
        return 'Child'
    elif age < 60:
        return 'Adult'
    else:
        return 'Senior'

df['age_group'] = df['age'].apply(categorize_age)

# 3. Compute survival rate per group
survival_by_age_group = df.groupby('age_group')['survived'].mean()

print("Survival Rate by Age Group:\n")
print(survival_by_age_group)

Survival Rate by Age Group:

age_group
Adult     0.364362
Child     0.539823
Senior    0.269231
Name: survived, dtype: float64


Q14. Error Analysis Simulation (Model Evaluation Thinking)

Context: Understanding prediction errors is key in ML.

Tasks:

1. Generate 1000 random error values using NumPy
2. Compute:
Mean
Standard deviation
3. Identify outliers:
Using mean ± 2*std
4. Explain:
What high variance means in model performance

In [22]:
import numpy as np

# 1. Generate 1000 random error values (mean=0, std=1)
np.random.seed(42)  # for reproducibility
errors = np.random.randn(1000)

# 2. Compute mean and standard deviation
mean_error = np.mean(errors)
std_error = np.std(errors)

print("Mean Error:", round(mean_error, 4))
print("Standard Deviation:", round(std_error, 4))

# 3. Identify outliers using mean ± 2*std
lower_bound = mean_error - 2 * std_error
upper_bound = mean_error + 2 * std_error

outliers = errors[(errors < lower_bound) | (errors > upper_bound)]

print("\nLower Bound:", round(lower_bound, 4))
print("Upper Bound:", round(upper_bound, 4))
print("Number of Outliers:", len(outliers))

Mean Error: 0.0193
Standard Deviation: 0.9787

Lower Bound: -1.9381
Upper Bound: 1.9768
Number of Outliers: 44


Q15. Business + ML Insight Problem (Tips Dataset)

Context: Convert data analysis into decision-making

Tasks:

1. Create:
tip_percentage
2. Group by:
day and time
3. Identify:
Highest revenue segment
4. Provide:
Recommendation for business strategy
How ML model can use this insight

In [24]:
df = sns.load_dataset('tips')

# 1. Create tip_percentage
df['tip_percentage'] = (df['tip'] / df['total_bill']) * 100

# 2. Group by day and time
grouped = df.groupby(['day', 'time']).agg({
    'total_bill': 'sum',
    'tip_percentage': 'mean'
}).reset_index()

print("Grouped Data:\n")
print(grouped)

max_revenue_row = grouped.loc[grouped['total_bill'].idxmax()]

print("\nHighest Revenue Segment:\n")
print(max_revenue_row)

Grouped Data:

    day    time  total_bill  tip_percentage
0  Thur   Lunch     1077.55       16.130074
1  Thur  Dinner       18.78       15.974441
2   Fri   Lunch       89.92       18.876489
3   Fri  Dinner      235.96       15.891611
4   Sat   Lunch        0.00             NaN
5   Sat  Dinner     1778.40       15.315172
6   Sun   Lunch        0.00             NaN
7   Sun  Dinner     1627.16       16.689729

Highest Revenue Segment:

day                     Sat
time                 Dinner
total_bill           1778.4
tip_percentage    15.315172
Name: 5, dtype: object


/var/folders/f2/j3l_llfs2fqgphpwqhb93j7w0000gn/T/ipykernel_36594/1549971219.py:7: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  grouped = df.groupby(['day', 'time']).agg({
